FROM golang:alpine

EXPOSE 8080

RUN apk add --no-cache git && \
    git clone https://github.com/docker-hy/material-applications.git && \
    cp -r material-applications/example-backend . && \
    rm -rf material-application

WORKDIR ./example-backend

ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build && \
    apk del git && \
    adduser -D appuser

USER appuser

CMD ./server
