FROM ubuntu:18.04

EXPOSE 5000

WORKDIR /usr/src/app

RUN apt update -y && \
    apt install -y curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash && \
    apt install -y nodejs && \
    apt install -y git && \
    git clone https://github.com/docker-hy/material-applications.git && \
    cp -r material-applications/example-frontend . && \
    rm -rf material-applications    

WORKDIR ./example-frontend

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install && \
    npm run build && \
    npm install -g serve && \
    apt-get purge -y --auto-remove curl && \
    apt-get purge -y --auto-remove git && \ 
    rm -rf /var/lib/apt/lists/* && \
    useradd -m appuser

USER appuser

CMD serve -s -l 5000 build 
