FROM ubuntu:18.04

EXPOSE 8080

WORKDIR /usr/local

RUN apt update -y && \
    apt install -y wget && \
    apt install -y git && \
    wget https://golang.org/dl/go1.16.8.linux-amd64.tar.gz && \
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.16.8.linux-amd64.tar.gz && \
    export PATH=$PATH:/usr/local/go/bin

WORKDIR /usr/src/app

RUN git clone https://github.com/docker-hy/material-applications.git && \
    cp -r material-applications/example-backend . && \
    rm -rf material-applications

WORKDIR ./example-backend

ENV REQUEST_ORIGIN=http://localhost:5000

RUN /usr/local/go/bin/go build && \
    useradd -m appuser && \
    apt-get purge -y --auto-remove wget && \
    apt-get purge -y --auto-remove git && \
    rm -rf /var/lib/apt/lists/*

USER appuser

CMD ./server
