FROM node:12-alpine as build-stage

EXPOSE 5000

WORKDIR /usr/src/app

RUN apk add --no-cache curl git && \
    git clone https://github.com/docker-hy/material-applications.git && \
    cp -r material-applications/example-frontend . && \
    rm -rf material-application

WORKDIR ./example-frontend

ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm install && \
    npm run build

FROM nginx:1.19-alpine

RUN apk add --no-cache npm && \
    npm install -g serve

COPY --from=build-stage /usr/src/app/example-frontend/build build/

CMD serve -s -l 5000 build
