version: '3'

services:
 frontend:
  image: example-frontend:1.14
  ports:
   - 5000:5000
  environment:
   - REACT_APP_BACKEND_URL=http://localhost:8080

 backend:
  image: example-backend:1.14
  ports:
   - 8080:8080
  environment:
   - REQUEST_ORIGIN=http://localhost
   - REDIS_HOST=redisserver 
   - POSTGRES_HOST=db
   - POSTGRES_USER=user
   - POSTGRES_PASSWORD=password
  
  depends_on:
   - db
 
 redisserver:
   image: redis
 
 db:
  image: postgres:13.2-alpine
  restart: unless-stopped
  environment:
   - POSTGRES_USER=user
   - POSTGRES_PASSWORD=password
  volumes:
   - ./database:/var/lib/postgresql/data

 nginx:
  image: nginx
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
   - 80:80
  depends_on:
   - frontend
   - backend
