version: '3'

services:
 frontend:
  image: example-frontend:1.14
  ports:
   - 5000:5000
  environment:
   - REACT_APP_BACKEND_URL=http://localhost:8080
  
 backend:
  image: example-backend:1.14
  ports:
   - 8080:8080
  environment:
   - REQUEST_ORIGIN=http://localhost:5000
